// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: event_notification_message.proto

package buff

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventJoinNotificationRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	NotificationReq  *NotificationRequest   `protobuf:"bytes,1,opt,name=notification_req,json=notificationReq,proto3" json:"notification_req,omitempty"`
	Body             *NotificationBody      `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	EventInfo        *EventInfo             `protobuf:"bytes,3,opt,name=event_info,json=eventInfo,proto3" json:"event_info,omitempty"`
	Requestor        *RequestorInfo         `protobuf:"bytes,4,opt,name=requestor,proto3" json:"requestor,omitempty"`
	ReceiverInfo     *ReceiverInfo          `protobuf:"bytes,5,opt,name=receiver_info,json=receiverInfo,proto3" json:"receiver_info,omitempty"`
	RequestTimeStamp *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=request_time_stamp,json=requestTimeStamp,proto3" json:"request_time_stamp,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *EventJoinNotificationRequest) Reset() {
	*x = EventJoinNotificationRequest{}
	mi := &file_event_notification_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventJoinNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventJoinNotificationRequest) ProtoMessage() {}

func (x *EventJoinNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_notification_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventJoinNotificationRequest.ProtoReflect.Descriptor instead.
func (*EventJoinNotificationRequest) Descriptor() ([]byte, []int) {
	return file_event_notification_message_proto_rawDescGZIP(), []int{0}
}

func (x *EventJoinNotificationRequest) GetNotificationReq() *NotificationRequest {
	if x != nil {
		return x.NotificationReq
	}
	return nil
}

func (x *EventJoinNotificationRequest) GetBody() *NotificationBody {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *EventJoinNotificationRequest) GetEventInfo() *EventInfo {
	if x != nil {
		return x.EventInfo
	}
	return nil
}

func (x *EventJoinNotificationRequest) GetRequestor() *RequestorInfo {
	if x != nil {
		return x.Requestor
	}
	return nil
}

func (x *EventJoinNotificationRequest) GetReceiverInfo() *ReceiverInfo {
	if x != nil {
		return x.ReceiverInfo
	}
	return nil
}

func (x *EventJoinNotificationRequest) GetRequestTimeStamp() *timestamppb.Timestamp {
	if x != nil {
		return x.RequestTimeStamp
	}
	return nil
}

type EventNotificationStatusRequest struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Id                      string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	NotificationId          string                 `protobuf:"bytes,2,opt,name=notification_id,json=notificationId,proto3" json:"notification_id,omitempty"`
	UserRequestorActivityId string                 `protobuf:"bytes,3,opt,name=user_requestor_activity_id,json=userRequestorActivityId,proto3" json:"user_requestor_activity_id,omitempty"`
	EventJoiner             []*EventJoiner         `protobuf:"bytes,4,rep,name=event_joiner,json=eventJoiner,proto3" json:"event_joiner,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *EventNotificationStatusRequest) Reset() {
	*x = EventNotificationStatusRequest{}
	mi := &file_event_notification_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventNotificationStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventNotificationStatusRequest) ProtoMessage() {}

func (x *EventNotificationStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_notification_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventNotificationStatusRequest.ProtoReflect.Descriptor instead.
func (*EventNotificationStatusRequest) Descriptor() ([]byte, []int) {
	return file_event_notification_message_proto_rawDescGZIP(), []int{1}
}

func (x *EventNotificationStatusRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EventNotificationStatusRequest) GetNotificationId() string {
	if x != nil {
		return x.NotificationId
	}
	return ""
}

func (x *EventNotificationStatusRequest) GetUserRequestorActivityId() string {
	if x != nil {
		return x.UserRequestorActivityId
	}
	return ""
}

func (x *EventNotificationStatusRequest) GetEventJoiner() []*EventJoiner {
	if x != nil {
		return x.EventJoiner
	}
	return nil
}

type EventNotificationStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	StatusCode    string                 `protobuf:"bytes,2,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventNotificationStatusResponse) Reset() {
	*x = EventNotificationStatusResponse{}
	mi := &file_event_notification_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventNotificationStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventNotificationStatusResponse) ProtoMessage() {}

func (x *EventNotificationStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_event_notification_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventNotificationStatusResponse.ProtoReflect.Descriptor instead.
func (*EventNotificationStatusResponse) Descriptor() ([]byte, []int) {
	return file_event_notification_message_proto_rawDescGZIP(), []int{2}
}

func (x *EventNotificationStatusResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EventNotificationStatusResponse) GetStatusCode() string {
	if x != nil {
		return x.StatusCode
	}
	return ""
}

func (x *EventNotificationStatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type EventInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	EventId        string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	EventName      string                 `protobuf:"bytes,2,opt,name=event_name,json=eventName,proto3" json:"event_name,omitempty"`
	EventCreatorId string                 `protobuf:"bytes,3,opt,name=event_creator_id,json=eventCreatorId,proto3" json:"event_creator_id,omitempty"`
	Status         string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Role           string                 `protobuf:"bytes,5,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EventInfo) Reset() {
	*x = EventInfo{}
	mi := &file_event_notification_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventInfo) ProtoMessage() {}

func (x *EventInfo) ProtoReflect() protoreflect.Message {
	mi := &file_event_notification_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventInfo.ProtoReflect.Descriptor instead.
func (*EventInfo) Descriptor() ([]byte, []int) {
	return file_event_notification_message_proto_rawDescGZIP(), []int{3}
}

func (x *EventInfo) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *EventInfo) GetEventName() string {
	if x != nil {
		return x.EventName
	}
	return ""
}

func (x *EventInfo) GetEventCreatorId() string {
	if x != nil {
		return x.EventCreatorId
	}
	return ""
}

func (x *EventInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *EventInfo) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type EventJoiner struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	DateJoined    string                 `protobuf:"bytes,4,opt,name=date_joined,json=dateJoined,proto3" json:"date_joined,omitempty"` // ISO 8601 format
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventJoiner) Reset() {
	*x = EventJoiner{}
	mi := &file_event_notification_message_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventJoiner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventJoiner) ProtoMessage() {}

func (x *EventJoiner) ProtoReflect() protoreflect.Message {
	mi := &file_event_notification_message_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventJoiner.ProtoReflect.Descriptor instead.
func (*EventJoiner) Descriptor() ([]byte, []int) {
	return file_event_notification_message_proto_rawDescGZIP(), []int{4}
}

func (x *EventJoiner) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *EventJoiner) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *EventJoiner) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *EventJoiner) GetDateJoined() string {
	if x != nil {
		return x.DateJoined
	}
	return ""
}

type EventVenue struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Name               string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Location           string                 `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
	Type               string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Latitude           float64                `protobuf:"fixed64,4,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude          float64                `protobuf:"fixed64,5,opt,name=longitude,proto3" json:"longitude,omitempty"`
	BookingEventStatus string                 `protobuf:"bytes,6,opt,name=booking_event_status,json=bookingEventStatus,proto3" json:"booking_event_status,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *EventVenue) Reset() {
	*x = EventVenue{}
	mi := &file_event_notification_message_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventVenue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventVenue) ProtoMessage() {}

func (x *EventVenue) ProtoReflect() protoreflect.Message {
	mi := &file_event_notification_message_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventVenue.ProtoReflect.Descriptor instead.
func (*EventVenue) Descriptor() ([]byte, []int) {
	return file_event_notification_message_proto_rawDescGZIP(), []int{5}
}

func (x *EventVenue) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EventVenue) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *EventVenue) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *EventVenue) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *EventVenue) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *EventVenue) GetBookingEventStatus() string {
	if x != nil {
		return x.BookingEventStatus
	}
	return ""
}

type EventOrganizer struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	OrganizerId      string                 `protobuf:"bytes,1,opt,name=organizer_id,json=organizerId,proto3" json:"organizer_id,omitempty"`
	OrganizerName    string                 `protobuf:"bytes,2,opt,name=organizer_name,json=organizerName,proto3" json:"organizer_name,omitempty"`
	OrganizerContact string                 `protobuf:"bytes,3,opt,name=organizer_contact,json=organizerContact,proto3" json:"organizer_contact,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *EventOrganizer) Reset() {
	*x = EventOrganizer{}
	mi := &file_event_notification_message_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventOrganizer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventOrganizer) ProtoMessage() {}

func (x *EventOrganizer) ProtoReflect() protoreflect.Message {
	mi := &file_event_notification_message_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventOrganizer.ProtoReflect.Descriptor instead.
func (*EventOrganizer) Descriptor() ([]byte, []int) {
	return file_event_notification_message_proto_rawDescGZIP(), []int{6}
}

func (x *EventOrganizer) GetOrganizerId() string {
	if x != nil {
		return x.OrganizerId
	}
	return ""
}

func (x *EventOrganizer) GetOrganizerName() string {
	if x != nil {
		return x.OrganizerName
	}
	return ""
}

func (x *EventOrganizer) GetOrganizerContact() string {
	if x != nil {
		return x.OrganizerContact
	}
	return ""
}

var File_event_notification_message_proto protoreflect.FileDescriptor

const file_event_notification_message_proto_rawDesc = "" +
	"\n" +
	" event_notification_message.proto\x12\fnotification\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1anotification_message.proto\"\x9e\x03\n" +
	"\x1cEventJoinNotificationRequest\x12L\n" +
	"\x10notification_req\x18\x01 \x01(\v2!.notification.NotificationRequestR\x0fnotificationReq\x122\n" +
	"\x04body\x18\x02 \x01(\v2\x1e.notification.NotificationBodyR\x04body\x126\n" +
	"\n" +
	"event_info\x18\x03 \x01(\v2\x17.notification.EventInfoR\teventInfo\x129\n" +
	"\trequestor\x18\x04 \x01(\v2\x1b.notification.RequestorInfoR\trequestor\x12?\n" +
	"\rreceiver_info\x18\x05 \x01(\v2\x1a.notification.ReceiverInfoR\freceiverInfo\x12H\n" +
	"\x12request_time_stamp\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\x10requestTimeStamp\"\xd4\x01\n" +
	"\x1eEventNotificationStatusRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12'\n" +
	"\x0fnotification_id\x18\x02 \x01(\tR\x0enotificationId\x12;\n" +
	"\x1auser_requestor_activity_id\x18\x03 \x01(\tR\x17userRequestorActivityId\x12<\n" +
	"\fevent_joiner\x18\x04 \x03(\v2\x19.notification.EventJoinerR\veventJoiner\"l\n" +
	"\x1fEventNotificationStatusResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vstatus_code\x18\x02 \x01(\tR\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\x9b\x01\n" +
	"\tEventInfo\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x1d\n" +
	"\n" +
	"event_name\x18\x02 \x01(\tR\teventName\x12(\n" +
	"\x10event_creator_id\x18\x03 \x01(\tR\x0eeventCreatorId\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x12\n" +
	"\x04role\x18\x05 \x01(\tR\x04role\"s\n" +
	"\vEventJoiner\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1f\n" +
	"\vdate_joined\x18\x04 \x01(\tR\n" +
	"dateJoined\"\xbc\x01\n" +
	"\n" +
	"EventVenue\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\blocation\x18\x02 \x01(\tR\blocation\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x1a\n" +
	"\blatitude\x18\x04 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x05 \x01(\x01R\tlongitude\x120\n" +
	"\x14booking_event_status\x18\x06 \x01(\tR\x12bookingEventStatus\"\x87\x01\n" +
	"\x0eEventOrganizer\x12!\n" +
	"\forganizer_id\x18\x01 \x01(\tR\vorganizerId\x12%\n" +
	"\x0eorganizer_name\x18\x02 \x01(\tR\rorganizerName\x12+\n" +
	"\x11organizer_contact\x18\x03 \x01(\tR\x10organizerContactB\aZ\x05buff/b\x06proto3"

var (
	file_event_notification_message_proto_rawDescOnce sync.Once
	file_event_notification_message_proto_rawDescData []byte
)

func file_event_notification_message_proto_rawDescGZIP() []byte {
	file_event_notification_message_proto_rawDescOnce.Do(func() {
		file_event_notification_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_event_notification_message_proto_rawDesc), len(file_event_notification_message_proto_rawDesc)))
	})
	return file_event_notification_message_proto_rawDescData
}

var file_event_notification_message_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_event_notification_message_proto_goTypes = []any{
	(*EventJoinNotificationRequest)(nil),    // 0: notification.EventJoinNotificationRequest
	(*EventNotificationStatusRequest)(nil),  // 1: notification.EventNotificationStatusRequest
	(*EventNotificationStatusResponse)(nil), // 2: notification.EventNotificationStatusResponse
	(*EventInfo)(nil),                       // 3: notification.EventInfo
	(*EventJoiner)(nil),                     // 4: notification.EventJoiner
	(*EventVenue)(nil),                      // 5: notification.EventVenue
	(*EventOrganizer)(nil),                  // 6: notification.EventOrganizer
	(*NotificationRequest)(nil),             // 7: notification.NotificationRequest
	(*NotificationBody)(nil),                // 8: notification.NotificationBody
	(*RequestorInfo)(nil),                   // 9: notification.RequestorInfo
	(*ReceiverInfo)(nil),                    // 10: notification.ReceiverInfo
	(*timestamppb.Timestamp)(nil),           // 11: google.protobuf.Timestamp
}
var file_event_notification_message_proto_depIdxs = []int32{
	7,  // 0: notification.EventJoinNotificationRequest.notification_req:type_name -> notification.NotificationRequest
	8,  // 1: notification.EventJoinNotificationRequest.body:type_name -> notification.NotificationBody
	3,  // 2: notification.EventJoinNotificationRequest.event_info:type_name -> notification.EventInfo
	9,  // 3: notification.EventJoinNotificationRequest.requestor:type_name -> notification.RequestorInfo
	10, // 4: notification.EventJoinNotificationRequest.receiver_info:type_name -> notification.ReceiverInfo
	11, // 5: notification.EventJoinNotificationRequest.request_time_stamp:type_name -> google.protobuf.Timestamp
	4,  // 6: notification.EventNotificationStatusRequest.event_joiner:type_name -> notification.EventJoiner
	7,  // [7:7] is the sub-list for method output_type
	7,  // [7:7] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_event_notification_message_proto_init() }
func file_event_notification_message_proto_init() {
	if File_event_notification_message_proto != nil {
		return
	}
	file_notification_message_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_event_notification_message_proto_rawDesc), len(file_event_notification_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_event_notification_message_proto_goTypes,
		DependencyIndexes: file_event_notification_message_proto_depIdxs,
		MessageInfos:      file_event_notification_message_proto_msgTypes,
	}.Build()
	File_event_notification_message_proto = out.File
	file_event_notification_message_proto_goTypes = nil
	file_event_notification_message_proto_depIdxs = nil
}
