// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: group_notification_message.proto

package buff

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GroupJoinNotificationRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	NotificationReq  *NotificationRequest   `protobuf:"bytes,1,opt,name=notification_req,json=notificationReq,proto3" json:"notification_req,omitempty"`
	Body             *NotificationBody      `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	GroupInfo        *GroupInfo             `protobuf:"bytes,3,opt,name=group_info,json=groupInfo,proto3" json:"group_info,omitempty"`
	Requestor        *RequestorInfo         `protobuf:"bytes,4,opt,name=requestor,proto3" json:"requestor,omitempty"`
	ReceiverInfo     *ReceiverInfo          `protobuf:"bytes,5,opt,name=receiver_info,json=receiverInfo,proto3" json:"receiver_info,omitempty"`
	RequestTimeStamp *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=request_time_stamp,json=requestTimeStamp,proto3" json:"request_time_stamp,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GroupJoinNotificationRequest) Reset() {
	*x = GroupJoinNotificationRequest{}
	mi := &file_group_notification_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupJoinNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupJoinNotificationRequest) ProtoMessage() {}

func (x *GroupJoinNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_group_notification_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupJoinNotificationRequest.ProtoReflect.Descriptor instead.
func (*GroupJoinNotificationRequest) Descriptor() ([]byte, []int) {
	return file_group_notification_message_proto_rawDescGZIP(), []int{0}
}

func (x *GroupJoinNotificationRequest) GetNotificationReq() *NotificationRequest {
	if x != nil {
		return x.NotificationReq
	}
	return nil
}

func (x *GroupJoinNotificationRequest) GetBody() *NotificationBody {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *GroupJoinNotificationRequest) GetGroupInfo() *GroupInfo {
	if x != nil {
		return x.GroupInfo
	}
	return nil
}

func (x *GroupJoinNotificationRequest) GetRequestor() *RequestorInfo {
	if x != nil {
		return x.Requestor
	}
	return nil
}

func (x *GroupJoinNotificationRequest) GetReceiverInfo() *ReceiverInfo {
	if x != nil {
		return x.ReceiverInfo
	}
	return nil
}

func (x *GroupJoinNotificationRequest) GetRequestTimeStamp() *timestamppb.Timestamp {
	if x != nil {
		return x.RequestTimeStamp
	}
	return nil
}

type GroupJoiner struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	DateJoined    string                 `protobuf:"bytes,4,opt,name=date_joined,json=dateJoined,proto3" json:"date_joined,omitempty"` // ISO 8601 format
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupJoiner) Reset() {
	*x = GroupJoiner{}
	mi := &file_group_notification_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupJoiner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupJoiner) ProtoMessage() {}

func (x *GroupJoiner) ProtoReflect() protoreflect.Message {
	mi := &file_group_notification_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupJoiner.ProtoReflect.Descriptor instead.
func (*GroupJoiner) Descriptor() ([]byte, []int) {
	return file_group_notification_message_proto_rawDescGZIP(), []int{1}
}

func (x *GroupJoiner) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GroupJoiner) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *GroupJoiner) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GroupJoiner) GetDateJoined() string {
	if x != nil {
		return x.DateJoined
	}
	return ""
}

type GroupInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	GroupId        string                 `protobuf:"bytes,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	GroupName      string                 `protobuf:"bytes,3,opt,name=group_name,json=groupName,proto3" json:"group_name,omitempty"`
	GroupCreatorId string                 `protobuf:"bytes,4,opt,name=group_creator_id,json=groupCreatorId,proto3" json:"group_creator_id,omitempty"`
	Status         string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	Role           string                 `protobuf:"bytes,6,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GroupInfo) Reset() {
	*x = GroupInfo{}
	mi := &file_group_notification_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupInfo) ProtoMessage() {}

func (x *GroupInfo) ProtoReflect() protoreflect.Message {
	mi := &file_group_notification_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupInfo.ProtoReflect.Descriptor instead.
func (*GroupInfo) Descriptor() ([]byte, []int) {
	return file_group_notification_message_proto_rawDescGZIP(), []int{2}
}

func (x *GroupInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GroupInfo) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *GroupInfo) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *GroupInfo) GetGroupCreatorId() string {
	if x != nil {
		return x.GroupCreatorId
	}
	return ""
}

func (x *GroupInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GroupInfo) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type GroupNotificationStatusRequest struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Id                      string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	NotificationId          string                 `protobuf:"bytes,2,opt,name=notification_id,json=notificationId,proto3" json:"notification_id,omitempty"`
	UserRequestorActivityId string                 `protobuf:"bytes,3,opt,name=user_requestor_activity_id,json=userRequestorActivityId,proto3" json:"user_requestor_activity_id,omitempty"`
	GroupJoiners            []*GroupJoiner         `protobuf:"bytes,4,rep,name=group_joiners,json=groupJoiners,proto3" json:"group_joiners,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *GroupNotificationStatusRequest) Reset() {
	*x = GroupNotificationStatusRequest{}
	mi := &file_group_notification_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupNotificationStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupNotificationStatusRequest) ProtoMessage() {}

func (x *GroupNotificationStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_group_notification_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupNotificationStatusRequest.ProtoReflect.Descriptor instead.
func (*GroupNotificationStatusRequest) Descriptor() ([]byte, []int) {
	return file_group_notification_message_proto_rawDescGZIP(), []int{3}
}

func (x *GroupNotificationStatusRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GroupNotificationStatusRequest) GetNotificationId() string {
	if x != nil {
		return x.NotificationId
	}
	return ""
}

func (x *GroupNotificationStatusRequest) GetUserRequestorActivityId() string {
	if x != nil {
		return x.UserRequestorActivityId
	}
	return ""
}

func (x *GroupNotificationStatusRequest) GetGroupJoiners() []*GroupJoiner {
	if x != nil {
		return x.GroupJoiners
	}
	return nil
}

type GroupNotificationStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	StatusCode    string                 `protobuf:"bytes,2,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupNotificationStatusResponse) Reset() {
	*x = GroupNotificationStatusResponse{}
	mi := &file_group_notification_message_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupNotificationStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupNotificationStatusResponse) ProtoMessage() {}

func (x *GroupNotificationStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_group_notification_message_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupNotificationStatusResponse.ProtoReflect.Descriptor instead.
func (*GroupNotificationStatusResponse) Descriptor() ([]byte, []int) {
	return file_group_notification_message_proto_rawDescGZIP(), []int{4}
}

func (x *GroupNotificationStatusResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GroupNotificationStatusResponse) GetStatusCode() string {
	if x != nil {
		return x.StatusCode
	}
	return ""
}

func (x *GroupNotificationStatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GroupReceiverInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserActivityId string                 `protobuf:"bytes,2,opt,name=user_activity_id,json=userActivityId,proto3" json:"user_activity_id,omitempty"`
	FirstName      string                 `protobuf:"bytes,3,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName       string                 `protobuf:"bytes,4,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	ProfilePic     string                 `protobuf:"bytes,5,opt,name=profile_pic,json=profilePic,proto3" json:"profile_pic,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GroupReceiverInfo) Reset() {
	*x = GroupReceiverInfo{}
	mi := &file_group_notification_message_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupReceiverInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupReceiverInfo) ProtoMessage() {}

func (x *GroupReceiverInfo) ProtoReflect() protoreflect.Message {
	mi := &file_group_notification_message_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupReceiverInfo.ProtoReflect.Descriptor instead.
func (*GroupReceiverInfo) Descriptor() ([]byte, []int) {
	return file_group_notification_message_proto_rawDescGZIP(), []int{5}
}

func (x *GroupReceiverInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GroupReceiverInfo) GetUserActivityId() string {
	if x != nil {
		return x.UserActivityId
	}
	return ""
}

func (x *GroupReceiverInfo) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *GroupReceiverInfo) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *GroupReceiverInfo) GetProfilePic() string {
	if x != nil {
		return x.ProfilePic
	}
	return ""
}

type GroupRequestorInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserActivityId string                 `protobuf:"bytes,2,opt,name=user_activity_id,json=userActivityId,proto3" json:"user_activity_id,omitempty"`
	FirstName      string                 `protobuf:"bytes,3,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName       string                 `protobuf:"bytes,4,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	ProfilePic     string                 `protobuf:"bytes,5,opt,name=profile_pic,json=profilePic,proto3" json:"profile_pic,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GroupRequestorInfo) Reset() {
	*x = GroupRequestorInfo{}
	mi := &file_group_notification_message_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupRequestorInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupRequestorInfo) ProtoMessage() {}

func (x *GroupRequestorInfo) ProtoReflect() protoreflect.Message {
	mi := &file_group_notification_message_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupRequestorInfo.ProtoReflect.Descriptor instead.
func (*GroupRequestorInfo) Descriptor() ([]byte, []int) {
	return file_group_notification_message_proto_rawDescGZIP(), []int{6}
}

func (x *GroupRequestorInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GroupRequestorInfo) GetUserActivityId() string {
	if x != nil {
		return x.UserActivityId
	}
	return ""
}

func (x *GroupRequestorInfo) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *GroupRequestorInfo) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *GroupRequestorInfo) GetProfilePic() string {
	if x != nil {
		return x.ProfilePic
	}
	return ""
}

var File_group_notification_message_proto protoreflect.FileDescriptor

const file_group_notification_message_proto_rawDesc = "" +
	"\n" +
	" group_notification_message.proto\x12\fnotification\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1anotification_message.proto\"\x9e\x03\n" +
	"\x1cGroupJoinNotificationRequest\x12L\n" +
	"\x10notification_req\x18\x01 \x01(\v2!.notification.NotificationRequestR\x0fnotificationReq\x122\n" +
	"\x04body\x18\x02 \x01(\v2\x1e.notification.NotificationBodyR\x04body\x126\n" +
	"\n" +
	"group_info\x18\x03 \x01(\v2\x17.notification.GroupInfoR\tgroupInfo\x129\n" +
	"\trequestor\x18\x04 \x01(\v2\x1b.notification.RequestorInfoR\trequestor\x12?\n" +
	"\rreceiver_info\x18\x05 \x01(\v2\x1a.notification.ReceiverInfoR\freceiverInfo\x12H\n" +
	"\x12request_time_stamp\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\x10requestTimeStamp\"s\n" +
	"\vGroupJoiner\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1f\n" +
	"\vdate_joined\x18\x04 \x01(\tR\n" +
	"dateJoined\"\xab\x01\n" +
	"\tGroupInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\tR\agroupId\x12\x1d\n" +
	"\n" +
	"group_name\x18\x03 \x01(\tR\tgroupName\x12(\n" +
	"\x10group_creator_id\x18\x04 \x01(\tR\x0egroupCreatorId\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x12\n" +
	"\x04role\x18\x06 \x01(\tR\x04role\"\xd6\x01\n" +
	"\x1eGroupNotificationStatusRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12'\n" +
	"\x0fnotification_id\x18\x02 \x01(\tR\x0enotificationId\x12;\n" +
	"\x1auser_requestor_activity_id\x18\x03 \x01(\tR\x17userRequestorActivityId\x12>\n" +
	"\rgroup_joiners\x18\x04 \x03(\v2\x19.notification.GroupJoinerR\fgroupJoiners\"l\n" +
	"\x1fGroupNotificationStatusResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vstatus_code\x18\x02 \x01(\tR\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\xaa\x01\n" +
	"\x11GroupReceiverInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12(\n" +
	"\x10user_activity_id\x18\x02 \x01(\tR\x0euserActivityId\x12\x1d\n" +
	"\n" +
	"first_name\x18\x03 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x04 \x01(\tR\blastName\x12\x1f\n" +
	"\vprofile_pic\x18\x05 \x01(\tR\n" +
	"profilePic\"\xab\x01\n" +
	"\x12GroupRequestorInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12(\n" +
	"\x10user_activity_id\x18\x02 \x01(\tR\x0euserActivityId\x12\x1d\n" +
	"\n" +
	"first_name\x18\x03 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x04 \x01(\tR\blastName\x12\x1f\n" +
	"\vprofile_pic\x18\x05 \x01(\tR\n" +
	"profilePicB\aZ\x05buff/b\x06proto3"

var (
	file_group_notification_message_proto_rawDescOnce sync.Once
	file_group_notification_message_proto_rawDescData []byte
)

func file_group_notification_message_proto_rawDescGZIP() []byte {
	file_group_notification_message_proto_rawDescOnce.Do(func() {
		file_group_notification_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_group_notification_message_proto_rawDesc), len(file_group_notification_message_proto_rawDesc)))
	})
	return file_group_notification_message_proto_rawDescData
}

var file_group_notification_message_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_group_notification_message_proto_goTypes = []any{
	(*GroupJoinNotificationRequest)(nil),    // 0: notification.GroupJoinNotificationRequest
	(*GroupJoiner)(nil),                     // 1: notification.GroupJoiner
	(*GroupInfo)(nil),                       // 2: notification.GroupInfo
	(*GroupNotificationStatusRequest)(nil),  // 3: notification.GroupNotificationStatusRequest
	(*GroupNotificationStatusResponse)(nil), // 4: notification.GroupNotificationStatusResponse
	(*GroupReceiverInfo)(nil),               // 5: notification.GroupReceiverInfo
	(*GroupRequestorInfo)(nil),              // 6: notification.GroupRequestorInfo
	(*NotificationRequest)(nil),             // 7: notification.NotificationRequest
	(*NotificationBody)(nil),                // 8: notification.NotificationBody
	(*RequestorInfo)(nil),                   // 9: notification.RequestorInfo
	(*ReceiverInfo)(nil),                    // 10: notification.ReceiverInfo
	(*timestamppb.Timestamp)(nil),           // 11: google.protobuf.Timestamp
}
var file_group_notification_message_proto_depIdxs = []int32{
	7,  // 0: notification.GroupJoinNotificationRequest.notification_req:type_name -> notification.NotificationRequest
	8,  // 1: notification.GroupJoinNotificationRequest.body:type_name -> notification.NotificationBody
	2,  // 2: notification.GroupJoinNotificationRequest.group_info:type_name -> notification.GroupInfo
	9,  // 3: notification.GroupJoinNotificationRequest.requestor:type_name -> notification.RequestorInfo
	10, // 4: notification.GroupJoinNotificationRequest.receiver_info:type_name -> notification.ReceiverInfo
	11, // 5: notification.GroupJoinNotificationRequest.request_time_stamp:type_name -> google.protobuf.Timestamp
	1,  // 6: notification.GroupNotificationStatusRequest.group_joiners:type_name -> notification.GroupJoiner
	7,  // [7:7] is the sub-list for method output_type
	7,  // [7:7] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_group_notification_message_proto_init() }
func file_group_notification_message_proto_init() {
	if File_group_notification_message_proto != nil {
		return
	}
	file_notification_message_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_group_notification_message_proto_rawDesc), len(file_group_notification_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_group_notification_message_proto_goTypes,
		DependencyIndexes: file_group_notification_message_proto_depIdxs,
		MessageInfos:      file_group_notification_message_proto_msgTypes,
	}.Build()
	File_group_notification_message_proto = out.File
	file_group_notification_message_proto_goTypes = nil
	file_group_notification_message_proto_depIdxs = nil
}
