// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: match_notification_message.proto

package buff

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JoinNotificationMatchRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	UserReceiverId      string                 `protobuf:"bytes,1,opt,name=user_receiver_id,json=userReceiverId,proto3" json:"user_receiver_id,omitempty"`
	UserRequestorInfo   *UserInfoRequestor     `protobuf:"bytes,2,opt,name=user_requestor_info,json=userRequestorInfo,proto3" json:"user_requestor_info,omitempty"`
	MatchInfo           *MatchInfo             `protobuf:"bytes,3,opt,name=match_info,json=matchInfo,proto3" json:"match_info,omitempty"`
	UserActivityId      string                 `protobuf:"bytes,4,opt,name=user_activity_id,json=userActivityId,proto3" json:"user_activity_id,omitempty"`
	NotificationTokenId string                 `protobuf:"bytes,5,opt,name=notification_token_id,json=notificationTokenId,proto3" json:"notification_token_id,omitempty"`
	DeviceType          string                 `protobuf:"bytes,6,opt,name=device_type,json=deviceType,proto3" json:"device_type,omitempty"`
	RequestTimeStamp    *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=request_time_stamp,json=requestTimeStamp,proto3" json:"request_time_stamp,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *JoinNotificationMatchRequest) Reset() {
	*x = JoinNotificationMatchRequest{}
	mi := &file_match_notification_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinNotificationMatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinNotificationMatchRequest) ProtoMessage() {}

func (x *JoinNotificationMatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_match_notification_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinNotificationMatchRequest.ProtoReflect.Descriptor instead.
func (*JoinNotificationMatchRequest) Descriptor() ([]byte, []int) {
	return file_match_notification_message_proto_rawDescGZIP(), []int{0}
}

func (x *JoinNotificationMatchRequest) GetUserReceiverId() string {
	if x != nil {
		return x.UserReceiverId
	}
	return ""
}

func (x *JoinNotificationMatchRequest) GetUserRequestorInfo() *UserInfoRequestor {
	if x != nil {
		return x.UserRequestorInfo
	}
	return nil
}

func (x *JoinNotificationMatchRequest) GetMatchInfo() *MatchInfo {
	if x != nil {
		return x.MatchInfo
	}
	return nil
}

func (x *JoinNotificationMatchRequest) GetUserActivityId() string {
	if x != nil {
		return x.UserActivityId
	}
	return ""
}

func (x *JoinNotificationMatchRequest) GetNotificationTokenId() string {
	if x != nil {
		return x.NotificationTokenId
	}
	return ""
}

func (x *JoinNotificationMatchRequest) GetDeviceType() string {
	if x != nil {
		return x.DeviceType
	}
	return ""
}

func (x *JoinNotificationMatchRequest) GetRequestTimeStamp() *timestamppb.Timestamp {
	if x != nil {
		return x.RequestTimeStamp
	}
	return nil
}

type JoinNotificationMatchResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	NotificationMsgId string                 `protobuf:"bytes,2,opt,name=notification_msg_id,json=notificationMsgId,proto3" json:"notification_msg_id,omitempty"`
	ResponseTimeStamp *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=response_time_stamp,json=responseTimeStamp,proto3" json:"response_time_stamp,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *JoinNotificationMatchResponse) Reset() {
	*x = JoinNotificationMatchResponse{}
	mi := &file_match_notification_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinNotificationMatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinNotificationMatchResponse) ProtoMessage() {}

func (x *JoinNotificationMatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_match_notification_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinNotificationMatchResponse.ProtoReflect.Descriptor instead.
func (*JoinNotificationMatchResponse) Descriptor() ([]byte, []int) {
	return file_match_notification_message_proto_rawDescGZIP(), []int{1}
}

func (x *JoinNotificationMatchResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *JoinNotificationMatchResponse) GetNotificationMsgId() string {
	if x != nil {
		return x.NotificationMsgId
	}
	return ""
}

func (x *JoinNotificationMatchResponse) GetResponseTimeStamp() *timestamppb.Timestamp {
	if x != nil {
		return x.ResponseTimeStamp
	}
	return nil
}

type MatchInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	MatchName     string                 `protobuf:"bytes,2,opt,name=match_name,json=matchName,proto3" json:"match_name,omitempty"`
	MatchDate     string                 `protobuf:"bytes,3,opt,name=match_date,json=matchDate,proto3" json:"match_date,omitempty"`
	LandMark      string                 `protobuf:"bytes,4,opt,name=land_mark,json=landMark,proto3" json:"land_mark,omitempty"`
	IsPaid        bool                   `protobuf:"varint,5,opt,name=is_paid,json=isPaid,proto3" json:"is_paid,omitempty"`
	MatchPrice    float32                `protobuf:"fixed32,6,opt,name=match_price,json=matchPrice,proto3" json:"match_price,omitempty"`
	StartHour     string                 `protobuf:"bytes,7,opt,name=start_hour,json=startHour,proto3" json:"start_hour,omitempty"`
	EndHour       string                 `protobuf:"bytes,8,opt,name=end_hour,json=endHour,proto3" json:"end_hour,omitempty"`
	MatchCategory string                 `protobuf:"bytes,9,opt,name=match_category,json=matchCategory,proto3" json:"match_category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchInfo) Reset() {
	*x = MatchInfo{}
	mi := &file_match_notification_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchInfo) ProtoMessage() {}

func (x *MatchInfo) ProtoReflect() protoreflect.Message {
	mi := &file_match_notification_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchInfo.ProtoReflect.Descriptor instead.
func (*MatchInfo) Descriptor() ([]byte, []int) {
	return file_match_notification_message_proto_rawDescGZIP(), []int{2}
}

func (x *MatchInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MatchInfo) GetMatchName() string {
	if x != nil {
		return x.MatchName
	}
	return ""
}

func (x *MatchInfo) GetMatchDate() string {
	if x != nil {
		return x.MatchDate
	}
	return ""
}

func (x *MatchInfo) GetLandMark() string {
	if x != nil {
		return x.LandMark
	}
	return ""
}

func (x *MatchInfo) GetIsPaid() bool {
	if x != nil {
		return x.IsPaid
	}
	return false
}

func (x *MatchInfo) GetMatchPrice() float32 {
	if x != nil {
		return x.MatchPrice
	}
	return 0
}

func (x *MatchInfo) GetStartHour() string {
	if x != nil {
		return x.StartHour
	}
	return ""
}

func (x *MatchInfo) GetEndHour() string {
	if x != nil {
		return x.EndHour
	}
	return ""
}

func (x *MatchInfo) GetMatchCategory() string {
	if x != nil {
		return x.MatchCategory
	}
	return ""
}

var File_match_notification_message_proto protoreflect.FileDescriptor

const file_match_notification_message_proto_rawDesc = "" +
	"\n" +
	" match_notification_message.proto\x12\fnotification\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1anotification_message.proto\"\x9a\x03\n" +
	"\x1cJoinNotificationMatchRequest\x12(\n" +
	"\x10user_receiver_id\x18\x01 \x01(\tR\x0euserReceiverId\x12O\n" +
	"\x13user_requestor_info\x18\x02 \x01(\v2\x1f.notification.UserInfoRequestorR\x11userRequestorInfo\x126\n" +
	"\n" +
	"match_info\x18\x03 \x01(\v2\x17.notification.MatchInfoR\tmatchInfo\x12(\n" +
	"\x10user_activity_id\x18\x04 \x01(\tR\x0euserActivityId\x122\n" +
	"\x15notification_token_id\x18\x05 \x01(\tR\x13notificationTokenId\x12\x1f\n" +
	"\vdevice_type\x18\x06 \x01(\tR\n" +
	"deviceType\x12H\n" +
	"\x12request_time_stamp\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\x10requestTimeStamp\"\xab\x01\n" +
	"\x1dJoinNotificationMatchResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12.\n" +
	"\x13notification_msg_id\x18\x02 \x01(\tR\x11notificationMsgId\x12J\n" +
	"\x13response_time_stamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x11responseTimeStamp\"\x91\x02\n" +
	"\tMatchInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"match_name\x18\x02 \x01(\tR\tmatchName\x12\x1d\n" +
	"\n" +
	"match_date\x18\x03 \x01(\tR\tmatchDate\x12\x1b\n" +
	"\tland_mark\x18\x04 \x01(\tR\blandMark\x12\x17\n" +
	"\ais_paid\x18\x05 \x01(\bR\x06isPaid\x12\x1f\n" +
	"\vmatch_price\x18\x06 \x01(\x02R\n" +
	"matchPrice\x12\x1d\n" +
	"\n" +
	"start_hour\x18\a \x01(\tR\tstartHour\x12\x19\n" +
	"\bend_hour\x18\b \x01(\tR\aendHour\x12%\n" +
	"\x0ematch_category\x18\t \x01(\tR\rmatchCategoryB\aZ\x05buff/b\x06proto3"

var (
	file_match_notification_message_proto_rawDescOnce sync.Once
	file_match_notification_message_proto_rawDescData []byte
)

func file_match_notification_message_proto_rawDescGZIP() []byte {
	file_match_notification_message_proto_rawDescOnce.Do(func() {
		file_match_notification_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_match_notification_message_proto_rawDesc), len(file_match_notification_message_proto_rawDesc)))
	})
	return file_match_notification_message_proto_rawDescData
}

var file_match_notification_message_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_match_notification_message_proto_goTypes = []any{
	(*JoinNotificationMatchRequest)(nil),  // 0: notification.JoinNotificationMatchRequest
	(*JoinNotificationMatchResponse)(nil), // 1: notification.JoinNotificationMatchResponse
	(*MatchInfo)(nil),                     // 2: notification.MatchInfo
	(*UserInfoRequestor)(nil),             // 3: notification.UserInfoRequestor
	(*timestamppb.Timestamp)(nil),         // 4: google.protobuf.Timestamp
}
var file_match_notification_message_proto_depIdxs = []int32{
	3, // 0: notification.JoinNotificationMatchRequest.user_requestor_info:type_name -> notification.UserInfoRequestor
	2, // 1: notification.JoinNotificationMatchRequest.match_info:type_name -> notification.MatchInfo
	4, // 2: notification.JoinNotificationMatchRequest.request_time_stamp:type_name -> google.protobuf.Timestamp
	4, // 3: notification.JoinNotificationMatchResponse.response_time_stamp:type_name -> google.protobuf.Timestamp
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_match_notification_message_proto_init() }
func file_match_notification_message_proto_init() {
	if File_match_notification_message_proto != nil {
		return
	}
	file_notification_message_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_match_notification_message_proto_rawDesc), len(file_match_notification_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_match_notification_message_proto_goTypes,
		DependencyIndexes: file_match_notification_message_proto_depIdxs,
		MessageInfos:      file_match_notification_message_proto_msgTypes,
	}.Build()
	File_match_notification_message_proto = out.File
	file_match_notification_message_proto_goTypes = nil
	file_match_notification_message_proto_depIdxs = nil
}
