// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: notification_message.proto

package buff

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NotificationBody struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Title            string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Body             string                 `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	ImageUrl         string                 `protobuf:"bytes,3,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	IsClicked        bool                   `protobuf:"varint,5,opt,name=is_clicked,json=isClicked,proto3" json:"is_clicked,omitempty"`
	Ttl              int32                  `protobuf:"varint,6,opt,name=ttl,proto3" json:"ttl,omitempty"`
	TimeStampRequest string                 `protobuf:"bytes,7,opt,name=time_stamp_request,json=timeStampRequest,proto3" json:"time_stamp_request,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *NotificationBody) Reset() {
	*x = NotificationBody{}
	mi := &file_notification_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationBody) ProtoMessage() {}

func (x *NotificationBody) ProtoReflect() protoreflect.Message {
	mi := &file_notification_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationBody.ProtoReflect.Descriptor instead.
func (*NotificationBody) Descriptor() ([]byte, []int) {
	return file_notification_message_proto_rawDescGZIP(), []int{0}
}

func (x *NotificationBody) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *NotificationBody) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *NotificationBody) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *NotificationBody) GetIsClicked() bool {
	if x != nil {
		return x.IsClicked
	}
	return false
}

func (x *NotificationBody) GetTtl() int32 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

func (x *NotificationBody) GetTimeStampRequest() string {
	if x != nil {
		return x.TimeStampRequest
	}
	return ""
}

type NotificationRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	NotificationType string                 `protobuf:"bytes,1,opt,name=notification_type,json=notificationType,proto3" json:"notification_type,omitempty"`
	Status           string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *NotificationRequest) Reset() {
	*x = NotificationRequest{}
	mi := &file_notification_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationRequest) ProtoMessage() {}

func (x *NotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationRequest.ProtoReflect.Descriptor instead.
func (*NotificationRequest) Descriptor() ([]byte, []int) {
	return file_notification_message_proto_rawDescGZIP(), []int{1}
}

func (x *NotificationRequest) GetNotificationType() string {
	if x != nil {
		return x.NotificationType
	}
	return ""
}

func (x *NotificationRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type UserInfoRequestor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FirstName     string                 `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	ProfilePic    string                 `protobuf:"bytes,4,opt,name=profile_pic,json=profilePic,proto3" json:"profile_pic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfoRequestor) Reset() {
	*x = UserInfoRequestor{}
	mi := &file_notification_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfoRequestor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfoRequestor) ProtoMessage() {}

func (x *UserInfoRequestor) ProtoReflect() protoreflect.Message {
	mi := &file_notification_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfoRequestor.ProtoReflect.Descriptor instead.
func (*UserInfoRequestor) Descriptor() ([]byte, []int) {
	return file_notification_message_proto_rawDescGZIP(), []int{2}
}

func (x *UserInfoRequestor) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserInfoRequestor) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *UserInfoRequestor) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *UserInfoRequestor) GetProfilePic() string {
	if x != nil {
		return x.ProfilePic
	}
	return ""
}

type ReceiverInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserActivityId string                 `protobuf:"bytes,2,opt,name=user_activity_id,json=userActivityId,proto3" json:"user_activity_id,omitempty"`
	FirstName      string                 `protobuf:"bytes,3,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName       string                 `protobuf:"bytes,4,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	ProfilePic     string                 `protobuf:"bytes,5,opt,name=profile_pic,json=profilePic,proto3" json:"profile_pic,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReceiverInfo) Reset() {
	*x = ReceiverInfo{}
	mi := &file_notification_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReceiverInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiverInfo) ProtoMessage() {}

func (x *ReceiverInfo) ProtoReflect() protoreflect.Message {
	mi := &file_notification_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiverInfo.ProtoReflect.Descriptor instead.
func (*ReceiverInfo) Descriptor() ([]byte, []int) {
	return file_notification_message_proto_rawDescGZIP(), []int{3}
}

func (x *ReceiverInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ReceiverInfo) GetUserActivityId() string {
	if x != nil {
		return x.UserActivityId
	}
	return ""
}

func (x *ReceiverInfo) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *ReceiverInfo) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *ReceiverInfo) GetProfilePic() string {
	if x != nil {
		return x.ProfilePic
	}
	return ""
}

type RequestorInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserActivityId string                 `protobuf:"bytes,2,opt,name=user_activity_id,json=userActivityId,proto3" json:"user_activity_id,omitempty"`
	FirstName      string                 `protobuf:"bytes,3,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName       string                 `protobuf:"bytes,4,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	ProfilePic     string                 `protobuf:"bytes,5,opt,name=profile_pic,json=profilePic,proto3" json:"profile_pic,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RequestorInfo) Reset() {
	*x = RequestorInfo{}
	mi := &file_notification_message_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestorInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestorInfo) ProtoMessage() {}

func (x *RequestorInfo) ProtoReflect() protoreflect.Message {
	mi := &file_notification_message_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestorInfo.ProtoReflect.Descriptor instead.
func (*RequestorInfo) Descriptor() ([]byte, []int) {
	return file_notification_message_proto_rawDescGZIP(), []int{4}
}

func (x *RequestorInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RequestorInfo) GetUserActivityId() string {
	if x != nil {
		return x.UserActivityId
	}
	return ""
}

func (x *RequestorInfo) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *RequestorInfo) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *RequestorInfo) GetProfilePic() string {
	if x != nil {
		return x.ProfilePic
	}
	return ""
}

var File_notification_message_proto protoreflect.FileDescriptor

const file_notification_message_proto_rawDesc = "" +
	"\n" +
	"\x1anotification_message.proto\x12\fnotification\"\xb8\x01\n" +
	"\x10NotificationBody\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x12\n" +
	"\x04body\x18\x02 \x01(\tR\x04body\x12\x1b\n" +
	"\timage_url\x18\x03 \x01(\tR\bimageUrl\x12\x1d\n" +
	"\n" +
	"is_clicked\x18\x05 \x01(\bR\tisClicked\x12\x10\n" +
	"\x03ttl\x18\x06 \x01(\x05R\x03ttl\x12,\n" +
	"\x12time_stamp_request\x18\a \x01(\tR\x10timeStampRequest\"Z\n" +
	"\x13NotificationRequest\x12+\n" +
	"\x11notification_type\x18\x01 \x01(\tR\x10notificationType\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"\x80\x01\n" +
	"\x11UserInfoRequestor\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"first_name\x18\x02 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x03 \x01(\tR\blastName\x12\x1f\n" +
	"\vprofile_pic\x18\x04 \x01(\tR\n" +
	"profilePic\"\xa5\x01\n" +
	"\fReceiverInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12(\n" +
	"\x10user_activity_id\x18\x02 \x01(\tR\x0euserActivityId\x12\x1d\n" +
	"\n" +
	"first_name\x18\x03 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x04 \x01(\tR\blastName\x12\x1f\n" +
	"\vprofile_pic\x18\x05 \x01(\tR\n" +
	"profilePic\"\xa6\x01\n" +
	"\rRequestorInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12(\n" +
	"\x10user_activity_id\x18\x02 \x01(\tR\x0euserActivityId\x12\x1d\n" +
	"\n" +
	"first_name\x18\x03 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x04 \x01(\tR\blastName\x12\x1f\n" +
	"\vprofile_pic\x18\x05 \x01(\tR\n" +
	"profilePicB\aZ\x05buff/b\x06proto3"

var (
	file_notification_message_proto_rawDescOnce sync.Once
	file_notification_message_proto_rawDescData []byte
)

func file_notification_message_proto_rawDescGZIP() []byte {
	file_notification_message_proto_rawDescOnce.Do(func() {
		file_notification_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_notification_message_proto_rawDesc), len(file_notification_message_proto_rawDesc)))
	})
	return file_notification_message_proto_rawDescData
}

var file_notification_message_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_notification_message_proto_goTypes = []any{
	(*NotificationBody)(nil),    // 0: notification.NotificationBody
	(*NotificationRequest)(nil), // 1: notification.NotificationRequest
	(*UserInfoRequestor)(nil),   // 2: notification.UserInfoRequestor
	(*ReceiverInfo)(nil),        // 3: notification.ReceiverInfo
	(*RequestorInfo)(nil),       // 4: notification.RequestorInfo
}
var file_notification_message_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_notification_message_proto_init() }
func file_notification_message_proto_init() {
	if File_notification_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_notification_message_proto_rawDesc), len(file_notification_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_notification_message_proto_goTypes,
		DependencyIndexes: file_notification_message_proto_depIdxs,
		MessageInfos:      file_notification_message_proto_msgTypes,
	}.Build()
	File_notification_message_proto = out.File
	file_notification_message_proto_goTypes = nil
	file_notification_message_proto_depIdxs = nil
}
