// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: notification_service.proto

package buff

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GroupNotificationService_RequestJoinGroupService_FullMethodName      = "/notification.GroupNotificationService/RequestJoinGroupService"
	GroupNotificationService_RequestUpdateGroupJoinStatus_FullMethodName = "/notification.GroupNotificationService/RequestUpdateGroupJoinStatus"
)

// GroupNotificationServiceClient is the client API for GroupNotificationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GroupNotificationServiceClient interface {
	RequestJoinGroupService(ctx context.Context, in *CreateGroupJoinRequest, opts ...grpc.CallOption) (*CreateGroupJoinResponse, error)
	RequestUpdateGroupJoinStatus(ctx context.Context, in *GroupStatusRequest, opts ...grpc.CallOption) (*GroupStatusResponse, error)
}

type groupNotificationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGroupNotificationServiceClient(cc grpc.ClientConnInterface) GroupNotificationServiceClient {
	return &groupNotificationServiceClient{cc}
}

func (c *groupNotificationServiceClient) RequestJoinGroupService(ctx context.Context, in *CreateGroupJoinRequest, opts ...grpc.CallOption) (*CreateGroupJoinResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateGroupJoinResponse)
	err := c.cc.Invoke(ctx, GroupNotificationService_RequestJoinGroupService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupNotificationServiceClient) RequestUpdateGroupJoinStatus(ctx context.Context, in *GroupStatusRequest, opts ...grpc.CallOption) (*GroupStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GroupStatusResponse)
	err := c.cc.Invoke(ctx, GroupNotificationService_RequestUpdateGroupJoinStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GroupNotificationServiceServer is the server API for GroupNotificationService service.
// All implementations must embed UnimplementedGroupNotificationServiceServer
// for forward compatibility.
type GroupNotificationServiceServer interface {
	RequestJoinGroupService(context.Context, *CreateGroupJoinRequest) (*CreateGroupJoinResponse, error)
	RequestUpdateGroupJoinStatus(context.Context, *GroupStatusRequest) (*GroupStatusResponse, error)
	mustEmbedUnimplementedGroupNotificationServiceServer()
}

// UnimplementedGroupNotificationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGroupNotificationServiceServer struct{}

func (UnimplementedGroupNotificationServiceServer) RequestJoinGroupService(context.Context, *CreateGroupJoinRequest) (*CreateGroupJoinResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestJoinGroupService not implemented")
}
func (UnimplementedGroupNotificationServiceServer) RequestUpdateGroupJoinStatus(context.Context, *GroupStatusRequest) (*GroupStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestUpdateGroupJoinStatus not implemented")
}
func (UnimplementedGroupNotificationServiceServer) mustEmbedUnimplementedGroupNotificationServiceServer() {
}
func (UnimplementedGroupNotificationServiceServer) testEmbeddedByValue() {}

// UnsafeGroupNotificationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GroupNotificationServiceServer will
// result in compilation errors.
type UnsafeGroupNotificationServiceServer interface {
	mustEmbedUnimplementedGroupNotificationServiceServer()
}

func RegisterGroupNotificationServiceServer(s grpc.ServiceRegistrar, srv GroupNotificationServiceServer) {
	// If the following call pancis, it indicates UnimplementedGroupNotificationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GroupNotificationService_ServiceDesc, srv)
}

func _GroupNotificationService_RequestJoinGroupService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGroupJoinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupNotificationServiceServer).RequestJoinGroupService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GroupNotificationService_RequestJoinGroupService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupNotificationServiceServer).RequestJoinGroupService(ctx, req.(*CreateGroupJoinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupNotificationService_RequestUpdateGroupJoinStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroupStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupNotificationServiceServer).RequestUpdateGroupJoinStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GroupNotificationService_RequestUpdateGroupJoinStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupNotificationServiceServer).RequestUpdateGroupJoinStatus(ctx, req.(*GroupStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GroupNotificationService_ServiceDesc is the grpc.ServiceDesc for GroupNotificationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GroupNotificationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "notification.GroupNotificationService",
	HandlerType: (*GroupNotificationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RequestJoinGroupService",
			Handler:    _GroupNotificationService_RequestJoinGroupService_Handler,
		},
		{
			MethodName: "RequestUpdateGroupJoinStatus",
			Handler:    _GroupNotificationService_RequestUpdateGroupJoinStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "notification_service.proto",
}

const (
	EventNotificationService_RequestCreateEventService_FullMethodName = "/notification.EventNotificationService/RequestCreateEventService"
	EventNotificationService_RequestUserJoinEvent_FullMethodName      = "/notification.EventNotificationService/RequestUserJoinEvent"
	EventNotificationService_RequestUpdateEventStatus_FullMethodName  = "/notification.EventNotificationService/RequestUpdateEventStatus"
)

// EventNotificationServiceClient is the client API for EventNotificationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EventNotificationServiceClient interface {
	RequestCreateEventService(ctx context.Context, in *CreateEventJoinRequest, opts ...grpc.CallOption) (*CreateEventJoinResponse, error)
	RequestUserJoinEvent(ctx context.Context, in *CreateEventJoinRequest, opts ...grpc.CallOption) (*CreateEventJoinResponse, error)
	RequestUpdateEventStatus(ctx context.Context, in *EventStatusRequest, opts ...grpc.CallOption) (*EventStatusResponse, error)
}

type eventNotificationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEventNotificationServiceClient(cc grpc.ClientConnInterface) EventNotificationServiceClient {
	return &eventNotificationServiceClient{cc}
}

func (c *eventNotificationServiceClient) RequestCreateEventService(ctx context.Context, in *CreateEventJoinRequest, opts ...grpc.CallOption) (*CreateEventJoinResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateEventJoinResponse)
	err := c.cc.Invoke(ctx, EventNotificationService_RequestCreateEventService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventNotificationServiceClient) RequestUserJoinEvent(ctx context.Context, in *CreateEventJoinRequest, opts ...grpc.CallOption) (*CreateEventJoinResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateEventJoinResponse)
	err := c.cc.Invoke(ctx, EventNotificationService_RequestUserJoinEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventNotificationServiceClient) RequestUpdateEventStatus(ctx context.Context, in *EventStatusRequest, opts ...grpc.CallOption) (*EventStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EventStatusResponse)
	err := c.cc.Invoke(ctx, EventNotificationService_RequestUpdateEventStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EventNotificationServiceServer is the server API for EventNotificationService service.
// All implementations must embed UnimplementedEventNotificationServiceServer
// for forward compatibility.
type EventNotificationServiceServer interface {
	RequestCreateEventService(context.Context, *CreateEventJoinRequest) (*CreateEventJoinResponse, error)
	RequestUserJoinEvent(context.Context, *CreateEventJoinRequest) (*CreateEventJoinResponse, error)
	RequestUpdateEventStatus(context.Context, *EventStatusRequest) (*EventStatusResponse, error)
	mustEmbedUnimplementedEventNotificationServiceServer()
}

// UnimplementedEventNotificationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEventNotificationServiceServer struct{}

func (UnimplementedEventNotificationServiceServer) RequestCreateEventService(context.Context, *CreateEventJoinRequest) (*CreateEventJoinResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestCreateEventService not implemented")
}
func (UnimplementedEventNotificationServiceServer) RequestUserJoinEvent(context.Context, *CreateEventJoinRequest) (*CreateEventJoinResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestUserJoinEvent not implemented")
}
func (UnimplementedEventNotificationServiceServer) RequestUpdateEventStatus(context.Context, *EventStatusRequest) (*EventStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestUpdateEventStatus not implemented")
}
func (UnimplementedEventNotificationServiceServer) mustEmbedUnimplementedEventNotificationServiceServer() {
}
func (UnimplementedEventNotificationServiceServer) testEmbeddedByValue() {}

// UnsafeEventNotificationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EventNotificationServiceServer will
// result in compilation errors.
type UnsafeEventNotificationServiceServer interface {
	mustEmbedUnimplementedEventNotificationServiceServer()
}

func RegisterEventNotificationServiceServer(s grpc.ServiceRegistrar, srv EventNotificationServiceServer) {
	// If the following call pancis, it indicates UnimplementedEventNotificationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EventNotificationService_ServiceDesc, srv)
}

func _EventNotificationService_RequestCreateEventService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateEventJoinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventNotificationServiceServer).RequestCreateEventService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventNotificationService_RequestCreateEventService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventNotificationServiceServer).RequestCreateEventService(ctx, req.(*CreateEventJoinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventNotificationService_RequestUserJoinEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateEventJoinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventNotificationServiceServer).RequestUserJoinEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventNotificationService_RequestUserJoinEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventNotificationServiceServer).RequestUserJoinEvent(ctx, req.(*CreateEventJoinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventNotificationService_RequestUpdateEventStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EventStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventNotificationServiceServer).RequestUpdateEventStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventNotificationService_RequestUpdateEventStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventNotificationServiceServer).RequestUpdateEventStatus(ctx, req.(*EventStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EventNotificationService_ServiceDesc is the grpc.ServiceDesc for EventNotificationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EventNotificationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "notification.EventNotificationService",
	HandlerType: (*EventNotificationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RequestCreateEventService",
			Handler:    _EventNotificationService_RequestCreateEventService_Handler,
		},
		{
			MethodName: "RequestUserJoinEvent",
			Handler:    _EventNotificationService_RequestUserJoinEvent_Handler,
		},
		{
			MethodName: "RequestUpdateEventStatus",
			Handler:    _EventNotificationService_RequestUpdateEventStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "notification_service.proto",
}
