// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: notification_service.proto

package buff

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateGroupJoinRequest struct {
	state            protoimpl.MessageState        `protogen:"open.v1"`
	GroupInfoRequest *GroupJoinNotificationRequest `protobuf:"bytes,1,opt,name=group_info_request,json=groupInfoRequest,proto3" json:"group_info_request,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateGroupJoinRequest) Reset() {
	*x = CreateGroupJoinRequest{}
	mi := &file_notification_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGroupJoinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGroupJoinRequest) ProtoMessage() {}

func (x *CreateGroupJoinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGroupJoinRequest.ProtoReflect.Descriptor instead.
func (*CreateGroupJoinRequest) Descriptor() ([]byte, []int) {
	return file_notification_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreateGroupJoinRequest) GetGroupInfoRequest() *GroupJoinNotificationRequest {
	if x != nil {
		return x.GroupInfoRequest
	}
	return nil
}

type CreateGroupJoinResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	IsGroupCreated bool                   `protobuf:"varint,1,opt,name=is_group_created,json=isGroupCreated,proto3" json:"is_group_created,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateGroupJoinResponse) Reset() {
	*x = CreateGroupJoinResponse{}
	mi := &file_notification_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGroupJoinResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGroupJoinResponse) ProtoMessage() {}

func (x *CreateGroupJoinResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notification_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGroupJoinResponse.ProtoReflect.Descriptor instead.
func (*CreateGroupJoinResponse) Descriptor() ([]byte, []int) {
	return file_notification_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateGroupJoinResponse) GetIsGroupCreated() bool {
	if x != nil {
		return x.IsGroupCreated
	}
	return false
}

type CreateEventJoinRequest struct {
	state            protoimpl.MessageState        `protogen:"open.v1"`
	EventInfoRequest *EventJoinNotificationRequest `protobuf:"bytes,1,opt,name=event_info_request,json=eventInfoRequest,proto3" json:"event_info_request,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateEventJoinRequest) Reset() {
	*x = CreateEventJoinRequest{}
	mi := &file_notification_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEventJoinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEventJoinRequest) ProtoMessage() {}

func (x *CreateEventJoinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEventJoinRequest.ProtoReflect.Descriptor instead.
func (*CreateEventJoinRequest) Descriptor() ([]byte, []int) {
	return file_notification_service_proto_rawDescGZIP(), []int{2}
}

func (x *CreateEventJoinRequest) GetEventInfoRequest() *EventJoinNotificationRequest {
	if x != nil {
		return x.EventInfoRequest
	}
	return nil
}

type CreateEventJoinResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	IsEventCreated bool                   `protobuf:"varint,1,opt,name=is_event_created,json=isEventCreated,proto3" json:"is_event_created,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateEventJoinResponse) Reset() {
	*x = CreateEventJoinResponse{}
	mi := &file_notification_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEventJoinResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEventJoinResponse) ProtoMessage() {}

func (x *CreateEventJoinResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notification_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEventJoinResponse.ProtoReflect.Descriptor instead.
func (*CreateEventJoinResponse) Descriptor() ([]byte, []int) {
	return file_notification_service_proto_rawDescGZIP(), []int{3}
}

func (x *CreateEventJoinResponse) GetIsEventCreated() bool {
	if x != nil {
		return x.IsEventCreated
	}
	return false
}

type EventStatusRequest struct {
	state                   protoimpl.MessageState          `protogen:"open.v1"`
	EventNotifStatusRequest *EventNotificationStatusRequest `protobuf:"bytes,1,opt,name=event_notif_status_request,json=eventNotifStatusRequest,proto3" json:"event_notif_status_request,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *EventStatusRequest) Reset() {
	*x = EventStatusRequest{}
	mi := &file_notification_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventStatusRequest) ProtoMessage() {}

func (x *EventStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventStatusRequest.ProtoReflect.Descriptor instead.
func (*EventStatusRequest) Descriptor() ([]byte, []int) {
	return file_notification_service_proto_rawDescGZIP(), []int{4}
}

func (x *EventStatusRequest) GetEventNotifStatusRequest() *EventNotificationStatusRequest {
	if x != nil {
		return x.EventNotifStatusRequest
	}
	return nil
}

type EventStatusResponse struct {
	state                    protoimpl.MessageState           `protogen:"open.v1"`
	EventNotifStatusResponse *EventNotificationStatusResponse `protobuf:"bytes,1,opt,name=event_notif_status_response,json=eventNotifStatusResponse,proto3" json:"event_notif_status_response,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *EventStatusResponse) Reset() {
	*x = EventStatusResponse{}
	mi := &file_notification_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventStatusResponse) ProtoMessage() {}

func (x *EventStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notification_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventStatusResponse.ProtoReflect.Descriptor instead.
func (*EventStatusResponse) Descriptor() ([]byte, []int) {
	return file_notification_service_proto_rawDescGZIP(), []int{5}
}

func (x *EventStatusResponse) GetEventNotifStatusResponse() *EventNotificationStatusResponse {
	if x != nil {
		return x.EventNotifStatusResponse
	}
	return nil
}

type GroupStatusRequest struct {
	state                   protoimpl.MessageState          `protogen:"open.v1"`
	GroupNotifStatusRequest *GroupNotificationStatusRequest `protobuf:"bytes,1,opt,name=group_notif_status_request,json=groupNotifStatusRequest,proto3" json:"group_notif_status_request,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *GroupStatusRequest) Reset() {
	*x = GroupStatusRequest{}
	mi := &file_notification_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupStatusRequest) ProtoMessage() {}

func (x *GroupStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupStatusRequest.ProtoReflect.Descriptor instead.
func (*GroupStatusRequest) Descriptor() ([]byte, []int) {
	return file_notification_service_proto_rawDescGZIP(), []int{6}
}

func (x *GroupStatusRequest) GetGroupNotifStatusRequest() *GroupNotificationStatusRequest {
	if x != nil {
		return x.GroupNotifStatusRequest
	}
	return nil
}

type GroupStatusResponse struct {
	state                    protoimpl.MessageState           `protogen:"open.v1"`
	GroupNotifStatusResponse *GroupNotificationStatusResponse `protobuf:"bytes,1,opt,name=group_notif_status_response,json=groupNotifStatusResponse,proto3" json:"group_notif_status_response,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *GroupStatusResponse) Reset() {
	*x = GroupStatusResponse{}
	mi := &file_notification_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupStatusResponse) ProtoMessage() {}

func (x *GroupStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notification_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupStatusResponse.ProtoReflect.Descriptor instead.
func (*GroupStatusResponse) Descriptor() ([]byte, []int) {
	return file_notification_service_proto_rawDescGZIP(), []int{7}
}

func (x *GroupStatusResponse) GetGroupNotifStatusResponse() *GroupNotificationStatusResponse {
	if x != nil {
		return x.GroupNotifStatusResponse
	}
	return nil
}

var File_notification_service_proto protoreflect.FileDescriptor

const file_notification_service_proto_rawDesc = "" +
	"\n" +
	"\x1anotification_service.proto\x12\fnotification\x1a event_notification_message.proto\x1a group_notification_message.proto\"r\n" +
	"\x16CreateGroupJoinRequest\x12X\n" +
	"\x12group_info_request\x18\x01 \x01(\v2*.notification.GroupJoinNotificationRequestR\x10groupInfoRequest\"C\n" +
	"\x17CreateGroupJoinResponse\x12(\n" +
	"\x10is_group_created\x18\x01 \x01(\bR\x0eisGroupCreated\"r\n" +
	"\x16CreateEventJoinRequest\x12X\n" +
	"\x12event_info_request\x18\x01 \x01(\v2*.notification.EventJoinNotificationRequestR\x10eventInfoRequest\"C\n" +
	"\x17CreateEventJoinResponse\x12(\n" +
	"\x10is_event_created\x18\x01 \x01(\bR\x0eisEventCreated\"\x7f\n" +
	"\x12EventStatusRequest\x12i\n" +
	"\x1aevent_notif_status_request\x18\x01 \x01(\v2,.notification.EventNotificationStatusRequestR\x17eventNotifStatusRequest\"\x83\x01\n" +
	"\x13EventStatusResponse\x12l\n" +
	"\x1bevent_notif_status_response\x18\x01 \x01(\v2-.notification.EventNotificationStatusResponseR\x18eventNotifStatusResponse\"\x7f\n" +
	"\x12GroupStatusRequest\x12i\n" +
	"\x1agroup_notif_status_request\x18\x01 \x01(\v2,.notification.GroupNotificationStatusRequestR\x17groupNotifStatusRequest\"\x83\x01\n" +
	"\x13GroupStatusResponse\x12l\n" +
	"\x1bgroup_notif_status_response\x18\x01 \x01(\v2-.notification.GroupNotificationStatusResponseR\x18groupNotifStatusResponse2\xeb\x01\n" +
	"\x18GroupNotificationService\x12h\n" +
	"\x17RequestJoinGroupService\x12$.notification.CreateGroupJoinRequest\x1a%.notification.CreateGroupJoinResponse\"\x00\x12e\n" +
	"\x1cRequestUpdateGroupJoinStatus\x12 .notification.GroupStatusRequest\x1a!.notification.GroupStatusResponse\"\x002\xd0\x02\n" +
	"\x18EventNotificationService\x12j\n" +
	"\x19RequestCreateEventService\x12$.notification.CreateEventJoinRequest\x1a%.notification.CreateEventJoinResponse\"\x00\x12e\n" +
	"\x14RequestUserJoinEvent\x12$.notification.CreateEventJoinRequest\x1a%.notification.CreateEventJoinResponse\"\x00\x12a\n" +
	"\x18RequestUpdateEventStatus\x12 .notification.EventStatusRequest\x1a!.notification.EventStatusResponse\"\x00B\aZ\x05buff/b\x06proto3"

var (
	file_notification_service_proto_rawDescOnce sync.Once
	file_notification_service_proto_rawDescData []byte
)

func file_notification_service_proto_rawDescGZIP() []byte {
	file_notification_service_proto_rawDescOnce.Do(func() {
		file_notification_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_notification_service_proto_rawDesc), len(file_notification_service_proto_rawDesc)))
	})
	return file_notification_service_proto_rawDescData
}

var file_notification_service_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_notification_service_proto_goTypes = []any{
	(*CreateGroupJoinRequest)(nil),          // 0: notification.CreateGroupJoinRequest
	(*CreateGroupJoinResponse)(nil),         // 1: notification.CreateGroupJoinResponse
	(*CreateEventJoinRequest)(nil),          // 2: notification.CreateEventJoinRequest
	(*CreateEventJoinResponse)(nil),         // 3: notification.CreateEventJoinResponse
	(*EventStatusRequest)(nil),              // 4: notification.EventStatusRequest
	(*EventStatusResponse)(nil),             // 5: notification.EventStatusResponse
	(*GroupStatusRequest)(nil),              // 6: notification.GroupStatusRequest
	(*GroupStatusResponse)(nil),             // 7: notification.GroupStatusResponse
	(*GroupJoinNotificationRequest)(nil),    // 8: notification.GroupJoinNotificationRequest
	(*EventJoinNotificationRequest)(nil),    // 9: notification.EventJoinNotificationRequest
	(*EventNotificationStatusRequest)(nil),  // 10: notification.EventNotificationStatusRequest
	(*EventNotificationStatusResponse)(nil), // 11: notification.EventNotificationStatusResponse
	(*GroupNotificationStatusRequest)(nil),  // 12: notification.GroupNotificationStatusRequest
	(*GroupNotificationStatusResponse)(nil), // 13: notification.GroupNotificationStatusResponse
}
var file_notification_service_proto_depIdxs = []int32{
	8,  // 0: notification.CreateGroupJoinRequest.group_info_request:type_name -> notification.GroupJoinNotificationRequest
	9,  // 1: notification.CreateEventJoinRequest.event_info_request:type_name -> notification.EventJoinNotificationRequest
	10, // 2: notification.EventStatusRequest.event_notif_status_request:type_name -> notification.EventNotificationStatusRequest
	11, // 3: notification.EventStatusResponse.event_notif_status_response:type_name -> notification.EventNotificationStatusResponse
	12, // 4: notification.GroupStatusRequest.group_notif_status_request:type_name -> notification.GroupNotificationStatusRequest
	13, // 5: notification.GroupStatusResponse.group_notif_status_response:type_name -> notification.GroupNotificationStatusResponse
	0,  // 6: notification.GroupNotificationService.RequestJoinGroupService:input_type -> notification.CreateGroupJoinRequest
	6,  // 7: notification.GroupNotificationService.RequestUpdateGroupJoinStatus:input_type -> notification.GroupStatusRequest
	2,  // 8: notification.EventNotificationService.RequestCreateEventService:input_type -> notification.CreateEventJoinRequest
	2,  // 9: notification.EventNotificationService.RequestUserJoinEvent:input_type -> notification.CreateEventJoinRequest
	4,  // 10: notification.EventNotificationService.RequestUpdateEventStatus:input_type -> notification.EventStatusRequest
	1,  // 11: notification.GroupNotificationService.RequestJoinGroupService:output_type -> notification.CreateGroupJoinResponse
	7,  // 12: notification.GroupNotificationService.RequestUpdateGroupJoinStatus:output_type -> notification.GroupStatusResponse
	3,  // 13: notification.EventNotificationService.RequestCreateEventService:output_type -> notification.CreateEventJoinResponse
	3,  // 14: notification.EventNotificationService.RequestUserJoinEvent:output_type -> notification.CreateEventJoinResponse
	5,  // 15: notification.EventNotificationService.RequestUpdateEventStatus:output_type -> notification.EventStatusResponse
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_notification_service_proto_init() }
func file_notification_service_proto_init() {
	if File_notification_service_proto != nil {
		return
	}
	file_event_notification_message_proto_init()
	file_group_notification_message_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_notification_service_proto_rawDesc), len(file_notification_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_notification_service_proto_goTypes,
		DependencyIndexes: file_notification_service_proto_depIdxs,
		MessageInfos:      file_notification_service_proto_msgTypes,
	}.Build()
	File_notification_service_proto = out.File
	file_notification_service_proto_goTypes = nil
	file_notification_service_proto_depIdxs = nil
}
