package cc

const (
	FIREBASE_ACCOUNT_JSON_FILE  = "firebase-service-account.json"
	GOOGLE_SERVICE_ACCOUNT_JSON = "google-services.json"
	FIREBASE_ACCOUNT_NAME       = "nxt-match-firebase"
	NOTIF_WANT_TO_JOIN          = "wants to join your group"
	NOTIF_WANT_TO_JOIN_EVENT    = "wants to join your event"
	NOTIF_WANTS_TO_JOIN_MATCH   = "wants to join your match"
	TITLE_EVENT_JOIN            = "Event Join Request"
	TITLE_GROUP_JOIN            = "Group Join Request"
	TITLE_MATCH_JOIN            = "Match Join Request"
	GROUP_JOIN_REQUEST_TYPE     = "join_group_request"
	EVENT_JOIN_REQUEST_TYPE     = "join_event_request"
	MATCH_JOIN_REQUEST_TYPE     = "join_match_request"
	ANDROID_NOTIFICATION_CLICK  = "ANDROID_NOTIFICATION_CLICK"
	MISSING_FIELDS              = "missing required fields"

	// status
	PENDING   = "pending"
	APPROVED  = "approved"
	REQUESTED = "requested"
	SUCCESS   = "success"
	REJECT    = "reject"
	FAIL      = "fail"

	// PATH VARIABLES
	NOTIFICATION_TOKEN_ID = "notification_token_id" // user + sha_id
	DEVICE_TOKEN_ID       = "device_token_id"       // device token generated by fcm
	CLIENT_ID             = "client_id"
	LAST_NOTIF_ID         = "last_notif_id"
	ID                    = "id"
	CURSOR                = "cursor"
	LIMIT                 = "limit"
	PLATFORM              = "platform"
	FCM_TOKEN             = "token"
	PAYLOAD               = "payload"

	// VARIABLES
	NXT_NOTIFS_MSG_ID = "nxt_notifications_msg_id"

	// SERVICES
	PROFILE_SERVICE       = "profile_service"
	EVENT_MANAGER_SERVICE = "event_manager_service"
	MAP_SERVICE           = "map_service"
)
